
branches:
  only:
  - master
  
clone_folder: c:\project\user_guide

image:
- Visual Studio 2017

configuration: Release

platform: x64


environment:
  global:
    PYTHON: C:\Python37-x64
    EPUBCHECK: https://github.com/w3c/epubcheck/releases/download/v4.2.2/epubcheck-4.2.2.zip


before_build:
- cmd: |-
    set PATH=%PYTHON%;%PATH%
    curl.exe -L -o echeck.zip %EPUBCHECK%
    7z x echeck.zip -y
    
build_script:
- cmd: |-
    python .\appveyor_scripts\build_guide.py

test_script:
- cmd: |-
    java -jar .\epubcheck-4.2.2\epubcheck.jar src/ -mode exp --failonwarnings
 

artifacts:
  - path: '*.epub'
    name: epub

deploy:
  - provider: GitHub
    auth_token:
      secure: QM747yzK0qkUTP1k/zQXGbxvvWK97YQpC5+6oAX6FTCPI+jYlB2zf4mzdcFj/uPL
    release: Sigil User Guide ($(APPVEYOR_REPO_TAG_NAME))
    tag: $(APPVEYOR_REPO_TAG_NAME)
    description: '[Replace this text]'
    artifact: epub
    draft: true
    on:
      branch: master
      APPVEYOR_REPO_TAG: true

